name: Call reusable workflows
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  # deprecated style
  call-reusable-workflow-with-string-input-deprecated:
    uses: ./.github/workflows/_reusable-workflow-with-deprected-style.yml
    with:
      string_input: "Hello, world."
  call-reusable-workflow-with-boolean-input-deprecated:
    uses: ./.github/workflows/_reusable-workflow-with-deprected-style.yml
    with:
      boolean_input: false
  call-reusable-workflow-with-number-input-deprecated:
    uses: ./.github/workflows/_reusable-workflow-with-deprected-style.yml
    with:
      number_input: 123
      
  # new style
  call-reusable-workflow-with-string-input-new:
    uses: ./.github/workflows/_reusable-workflow-with-new-style.yml
    with:
      string_input: "Hello, world."
  call-reusable-workflow-with-boolean-input-new:
    uses: ./.github/workflows/_reusable-workflow-with-new-style.yml
    with:
      boolean_input: false
  call-reusable-workflow-with-number-input-new:
    uses: ./.github/workflows/_reusable-workflow-with-new-style.yml
    with:
      number_input: 123
