name: "Comment to a merged pull request if the jobs are passed"

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: "Job 1"
        run: echo "Job 1"
  
  comment:
    needs: [ "job1" ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Get the commit hash of the merged pull request"
        id: get_commit_hash
        run: |
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      # Get the pull request number from the commit hash using github-script
      - name: "Search the pull request number by the commit hash of the merged pull request"
        id: get_pr_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const commit_hash = "${{ steps.get_commit_hash.outputs.commit_hash }}";
            const { data: { items } } = await github.rest.search.issuesAndPullRequests({
              q: `${commit_hash} type:pr is:merged`
            });
            const pr_number = items[0].number;
            console.log(`The pull request number is ${pr_number}`);
            return pr_number;
      - name: "Comment to the pull request"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
          script: |
            const pr_number = "${{ steps.get_pr_number.outputs.result }}";
            const { data: { html_url } } = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: "The jobs are passed!"
            });
