name: "Test gateway experiment"

on:
  workflow_dispatch:
    inputs:
      github_environment:
        description: GitHub Environment to use for this test run
        required: true
        type: choice
        options:
          - test-gateway
          - test-gateway-no-reviewers
        default: test-gateway
      target:
        description: mock target
        required: true
        type: choice
        options:
          - pipeline-1
          - pipeline-2
          - pipeline-3

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: ${{ inputs.github_environment }}
      deployment: ${{ inputs.github_environment == 'test-gateway' }}
    name: "Deploy (${{ inputs.github_environment }}, ${{ inputs.target }})"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Prove run context
        run: |
          echo "Environment: ${GITHUB_ENVIRONMENT} (from workflow job configuration)"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Ref: ${GITHUB_REF}"
        env:
          GITHUB_ENVIRONMENT: ${{ inputs.github_environment }}
